version: '3.8'

services:
  wikifetch:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    volumes:
      - wikifetch_data:/app/data
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/wikifetch.db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  wikifetch_data:
