version: '3.8'

services:
  wikifetch:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - wikifetch_data:/app/data
    environment:
      - FLASK_ENV=development
      - DATABASE_PATH=/app/data/wikifetch.db
    restart: unless-stopped

volumes:
  wikifetch_data:
